import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';




export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Navbar/>

    

      <h1>This is hompage ok</h1>

      <Footer/>
    </div>
  )
}
